version: 2.1

jobs:
  build-mac:
    macos:
      xcode: 26.4.0
    resource_class: m4pro.medium
    steps:
      - checkout
      - run:
          name: Message
          command: echo "It works"
  build-and-testtwo:
    docker:
      - image: "cimg/node:current"
    steps:
      - checkout
      - run:
          name: Message
          command: node --version

workflows:
  version: 2
  sample:
    jobs:
      - build-mac
  sampletwo:
    jobs:
      - build-and-testtwo
  
