version: 2.1

jobs:
  echo-project-slug:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Echo Project Slug
          command: echo << pipeline.project.slug >>

workflows:
  version: 2
  test:
    jobs:
      - echo-project-slug
